user_pref("extensions.zotero.translators.better-bibtex.skipFields",
          "abstract,annotation,copyright,eprint,eprinttype,file,isbn,issn,keywords,langid,month,pmc,pmcid,pmid,shorttitle");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.cite.automaticJournalAbbreviations", false);
user_pref("extensions.zotero.export.noteQuickCopy.setting", "{\"mode\":\"export\",\"id\":\"a45eca67-1ee8-45e5-b4c6-23fb8a852873\"}");
user_pref("extensions.zotero.export.quickCopy.setting", "export=ca65189f-8815-4afe-8c8b-8c7c15f0edca");
user_pref("extensions.zotero.lastAbstractExpand", false);
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.newItemTypeMRU", "journalArticle");
user_pref("extensions.zotero.pane.persist", "{\"zotero-collections-pane\":{},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{\"width\":\"457\"},\"zotero-items-tree\":{\"current-view-group\":\"default\"},\"zotero-items-column-title\":{\"width\":287,\"ordinal\":14.25,\"hidden\":false},\"zotero-items-column-firstCreator\":{\"width\":102,\"ordinal\":0.25,\"hidden\":false},\"zotero-items-column-itemType\":{\"width\":40,\"ordinal\":0.75,\"hidden\":true},\"zotero-items-column-date\":{\"ordinal\":1.25,\"hidden\":true},\"zotero-items-column-year\":{\"width\":50,\"ordinal\":1.75,\"hidden\":false},\"zotero-items-column-publisher\":{\"ordinal\":2.25,\"hidden\":true},\"zotero-items-column-publicationTitle\":{\"ordinal\":2.75,\"hidden\":false},\"zotero-items-column-journalAbbreviation\":{\"ordinal\":3.25,\"hidden\":true},\"zotero-items-column-language\":{\"ordinal\":3.75,\"hidden\":true},\"zotero-items-column-accessDate\":{\"ordinal\":4.25,\"hidden\":true},\"zotero-items-column-libraryCatalog\":{\"ordinal\":4.75,\"hidden\":true},\"zotero-items-column-callNumber\":{\"ordinal\":5.25,\"hidden\":true},\"zotero-items-column-rights\":{\"ordinal\":5.75,\"hidden\":true},\"zotero-items-column-dateAdded\":{\"ordinal\":6.25,\"hidden\":true},\"zotero-items-column-dateModified\":{\"ordinal\":6.75,\"hidden\":true},\"zotero-items-column-archive\":{\"ordinal\":7.25,\"hidden\":true},\"zotero-items-column-archiveLocation\":{\"ordinal\":7.75,\"hidden\":true},\"zotero-items-column-place\":{\"ordinal\":8.25,\"hidden\":true},\"zotero-items-column-volume\":{\"ordinal\":8.75,\"hidden\":true},\"zotero-items-column-edition\":{\"ordinal\":9.25,\"hidden\":true},\"zotero-items-column-pages\":{\"ordinal\":9.75,\"hidden\":true},\"zotero-items-column-issue\":{\"ordinal\":10.25,\"hidden\":true},\"zotero-items-column-series\":{\"ordinal\":10.75,\"hidden\":true},\"zotero-items-column-seriesTitle\":{\"ordinal\":11.25,\"hidden\":true},\"zotero-items-column-court\":{\"ordinal\":11.75,\"hidden\":true},\"zotero-items-column-medium\":{\"ordinal\":12.25,\"hidden\":true},\"zotero-items-column-genre\":{\"ordinal\":12.75,\"hidden\":true},\"zotero-items-column-system\":{\"ordinal\":13.25,\"hidden\":true},\"zotero-items-column-extra\":{\"ordinal\":13.75,\"hidden\":true},\"zotero-items-column-hasAttachment\":{\"ordinal\":14.75,\"hidden\":true},\"zotero-items-column-numNotes\":{\"ordinal\":15.25,\"hidden\":true},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"339\",\"height\":\"300\"},\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 5);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"L1\",\"sessionID\":\"gJWHnyhp\"}]");
user_pref("extensions.zotero.sync.fulltext.enabled", false);
user_pref("extensions.zotero.translators.better-bibtex.DOIandURL", "doi");
user_pref("extensions.zotero.translators.better-bibtex.bibtexParticleNoOp", true);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "[auth][year]");
user_pref("extensions.zotero.translators.better-bibtex.keyConflictPolicy", "change");
user_pref("extensions.zotero.translators.better-bibtex.platform", "win");
user_pref("extensions.zotero.translators.better-bibtex.quickCopyMode", "pandoc");
user_pref("extensions.zotero.useDataDir", true);
user_pref("intl.accept_languages", "en-GB, en");
